# Generated by Django 5.2 on 2025-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annotation', models.CharField(max_length=255)),
                ('link_to_work', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=255)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
