# Generated by Django 5.2.2 on 2025-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="link_to_work",
            field=models.CharField(default="Not found", max_length=255),
        ),
    ]
