# Generated by Django 5.2.2 on 2025-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_confirmation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmationlogin",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailconfirmationlogin",
            name="attempt_number",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
