# Generated by Django 5.2 on 2025-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_confirmation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmationlogin",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="emailconfirmationlogin",
            name="session_id",
            field=models.CharField(
                db_index=True, default="session_not_set", editable=False, max_length=255
            ),
            preserve_default=False,
        ),
    ]
