# Generated by Django 5.2.2 on 2025-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_confirmation", "0002_emailconfirmationlogin_locked_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmationlogin",
            name="used_at",
            field=models.DateTimeField(null=True),
        ),
    ]
