# Generated by Django 5.2.2 on 2025-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='reason_blocked',
            field=models.TextField(default='Значение по умолчанию'),
        ),
    ]
