services:
  postgresql:
    container_name: contest_backend_postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: contest_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_service" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
  minio-service:
    image: minio/minio:latest
    container_name: s3_minio
    volumes:
      - ./storage/minio:/data
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin-strong
    command: server --address ":9099" --console-address ":9000" /data
    restart: unless-stopped