# Generated by Django 5.2 on 2025-05-25 14:46

from django.db import migrations, models

contest_category_list = ["Фото", "Искусство", "наука"]


def add_contest_category(apps, schema_editor):
    ContestCategories = apps.get_model("contest_categories", "ContestCategories")
    for name in contest_category_list:
        ContestCategories.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContestCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "contest_category",
            },
        ),
        migrations.RunPython(add_contest_category),
    ]
