# Generated by Django 5.2 on 2025-05-16 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
        ("contests", "0003_contest_winner_list"),
        ("winners", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="winners",
            unique_together={("contest", "application")},
        ),
        migrations.RemoveField(
            model_name="winners",
            name="age_category",
        ),
        migrations.RemoveField(
            model_name="winners",
            name="nomination",
        ),
    ]
