# Generated by Django 5.2 on 2025-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkNewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=255, verbose_name='URL изображения')),
                ('height', models.IntegerField(verbose_name='Высота изображения')),
                ('width', models.IntegerField(verbose_name='Ширина изображения')),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vk_news_attachments',
            },
        ),
    ]
