# Generated by Django 5.2 on 2025-05-10 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
        ("criteria", "0001_initial"),
        ("work_rate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workrate",
            old_name="application_id",
            new_name="application",
        ),
        migrations.RenameField(
            model_name="workrate",
            old_name="criteria_id",
            new_name="criteria",
        ),
        migrations.AlterUniqueTogether(
            name="workrate",
            unique_together={("criteria", "application")},
        ),
    ]
