# Generated by Django 5.2 on 2025-06-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
        ("criteria", "0002_alter_criteria_name_and_more"),
        ("participants", "0002_alter_participant_unique_together"),
        ("work_rate", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workrate",
            name="jury",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="participants.participant",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="workrate",
            unique_together={("criteria", "application", "jury")},
        ),
    ]
