# Generated by Django 5.2 on 2025-05-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("age_categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="age_categories.agecategories",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
    ]
