# Generated by Django 5.2 on 2025-04-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("contests", "0001_initial"),
        ("nomination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_set",
                to="contests.contest",
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="nominations",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_set",
                to="nomination.nominations",
            ),
        ),
    ]
