# Generated by Django 5.2 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("birth_date", models.DateField()),
                ("password", models.CharField(max_length=255)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar_link",
                    models.CharField(
                        default="http://localhost:3000/static/images/default_avatar.jpg",
                        max_length=255,
                    ),
                ),
                ("education_or_work", models.CharField(default="None", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "competencies",
                    models.ManyToManyField(
                        related_name="user_competencies", to="competencies.competencies"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
