# Generated by Django 5.2.2 on 2025-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar_link",
            field=models.CharField(
                default="https://storage.yandexcloud.net/skazka-design/avatars/0463135f-1ca2-4ae6-a35a-729b0c914a87.jpeg",
                max_length=255,
            ),
        ),
    ]
