# Generated by Django 5.2 on 2025-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="education_or_work",
            field=models.CharField(default="Отсутствует", max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="middle_name",
            field=models.CharField(default="Отсутствует", max_length=255),
        ),
    ]
