# Generated by Django 5.2 on 2025-05-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contest_nominations", "0001_initial"),
        ("contests", "0001_initial"),
        ("nomination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestnominations",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.contest"
            ),
        ),
        migrations.AddField(
            model_name="contestnominations",
            name="nomination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nomination.nominations"
            ),
        ),
    ]
