# Generated by Django 5.2 on 2025-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('file_formats', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'file_constraint',
            },
        ),
    ]
