# Generated by Django 5.2 on 2025-05-30 21:10

from django.db import migrations, models

def create_file_constraints(apps, schema_editor):
    FileConstraint = apps.get_model("file_constraints", "FileConstraint")

    file_constraints = [
        {"name": "Images", "file_format": "jpeg,jpg,png,webp"},
        {"name": "Videos", "file_format": "mp4,webm"},
        {"name": "Text", "file_format": "docx,txt,pdf"},
    ]

    for file_constraint in file_constraints:
        FileConstraint.objects.get_or_create(**file_constraint)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=255, unique=True)),
                ("file_formats", models.TextField(editable=False)),
            ],
            options={
                "db_table": "file_constraint",
            },
        ),
        migrations.RunPython()
    ]
