# Generated by Django 5.2 on 2025-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("start_age", models.PositiveIntegerField(default=0)),
                ("end_age", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "age_categories",
            },
        ),
    ]
