# Generated by Django 5.2 on 2025-06-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0003_contest_file_constraints"),
        ("file_constraints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestFileConstraints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contest",
                    ),
                ),
                (
                    "file_constraints",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_constraints.fileconstraint",
                    ),
                ),
            ],
            options={
                "db_table": "contest_file_constraints",
                "unique_together": {("contest", "file_constraints")},
            },
        ),
    ]
