# Generated by Django 5.2 on 2025-05-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("age_categories", "0001_initial"),
        ("contest_categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("avatar", models.CharField(default=" ", max_length=255)),
                ("link_to_rules", models.CharField(max_length=255)),
                ("organizer", models.CharField(max_length=255)),
                ("prizes", models.TextField()),
                ("contacts_for_participants", models.CharField(max_length=255)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "age_category",
                    models.ManyToManyField(
                        related_name="contest_age_categories",
                        to="age_categories.agecategories",
                    ),
                ),
                (
                    "contest_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest_categories.contestcategories",
                    ),
                ),
            ],
            options={
                "db_table": "contests",
            },
        ),
    ]
