# Generated by Django 5.2 on 2025-04-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("contest_categories", "0001_initial"),
        ("criterias", "0001_initial"),
        ("nomination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("link_to_rules", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("organizer", models.CharField(max_length=255)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="contest_nominations",
                        through="categories.Categories",
                        to="nomination.nominations",
                    ),
                ),
                (
                    "contest_categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest_categories.contestcategories",
                    ),
                ),
                (
                    "criteria",
                    models.ManyToManyField(
                        related_name="contest_criteria", to="criterias.criteria"
                    ),
                ),
            ],
            options={
                "db_table": "contests",
            },
        ),
    ]
