# Generated by Django 5.2 on 2025-05-10 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contest_stage", "0001_initial"),
        ("contests", "0001_initial"),
        ("contests_contest_stage", "0001_initial"),
        ("criteria", "0001_initial"),
        ("nomination", "0001_initial"),
        ("participants", "0001_initial"),
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="contest_stage",
            field=models.ManyToManyField(
                related_name="contest_stages",
                through="contests_contest_stage.ContestsContestStage",
                through_fields=("contest", "stage"),
                to="contest_stage.conteststage",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="criteria",
            field=models.ManyToManyField(
                related_name="contest_criteria", to="criteria.criteria"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="nominations",
            field=models.ManyToManyField(
                related_name="contest_nominations", to="nomination.nominations"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="participants",
            field=models.ManyToManyField(
                related_name="contest_participants",
                through="participants.Participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="regions.region"
            ),
        ),
    ]
