# Generated by Django 5.2 on 2025-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
