# Generated by Django 5.2 on 2025-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
        ("contests", "0002_initial"),
        ("winners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="winner_list",
            field=models.ManyToManyField(
                related_name="contest_winners",
                through="winners.Winners",
                to="applications.applications",
            ),
        ),
    ]
