# Generated by Django 5.2 on 2025-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest_file_constraints", "0001_initial"),
        ("contests", "0003_contest_file_constraints"),
        ("file_constraints", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="file_constraints",
        ),
        migrations.AddField(
            model_name="contest",
            name="file_constraint",
            field=models.ManyToManyField(
                related_name="contest_file_constraints",
                through="contest_file_constraints.ContestFileConstraints",
                to="file_constraints.fileconstraint",
            ),
        ),
    ]
