# Generated by Django 5.2 on 2025-05-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_winner_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contest_categories',
            new_name='contest_category',
        ),
    ]
