# Generated by Django 5.2 on 2025-04-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest_stage", "0001_initial"),
        ("contests", "0003_contest_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="contest_stage",
            field=models.ManyToManyField(
                related_name="contest_stage", to="contest_stage.conteststage"
            ),
        ),
    ]
