# Generated by Django 5.2 on 2025-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_contest_contest_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="avatar",
            field=models.CharField(default=" ", max_length=255),
        ),
    ]
