# Generated by Django 5.2 on 2025-04-27 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0005_contest_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="date_start",
        ),
    ]
